package com.luck.picture.lib.config;

import android.os.Parcel;
import android.os.Parcelable;
import android.support.v4.media.session.PlaybackStateCompat;
import com.luck.picture.lib.R$style;
import com.luck.picture.lib.entity.LocalMedia;
import com.luck.picture.lib.style.PictureCropParameterStyle;
import com.luck.picture.lib.style.PictureWindowAnimationStyle;
import com.tencent.connect.common.Constants;
import defpackage.a22;
import defpackage.ew1;
import defpackage.k01;
import defpackage.ol2;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;

/* JADX INFO: loaded from: classes3.dex */
public final class PictureSelectionConfig implements Parcelable {
    public static PictureCropParameterStyle u1;
    public static k01 w1;
    public static ew1 x1;
    public boolean A0;
    public boolean B0;
    public boolean C0;
    public boolean D0;
    public boolean E0;
    public int F;
    public boolean F0;
    public int G;
    public boolean G0;
    public int H;
    public com.yalantis.ucrop.b.a H0;
    public int I;
    public List I0;
    public int J;
    public HashSet J0;
    public int K;
    public String K0;
    public int L;
    public boolean L0;
    public int M;
    public boolean M0;
    public int N;
    public boolean N0;
    public int O;
    public boolean O0;
    public int P;
    public int P0;
    public int Q;
    public int Q0;
    public int R;
    public int R0;
    public float S;
    public int S0;
    public long T;
    public int T0;
    public long U;
    public int U0;
    public int V;
    public int V0;
    public boolean W;
    public String W0;
    public boolean X;
    public String X0;
    public boolean Y;
    public String Y0;
    public boolean Z;
    public String Z0;
    public int a;
    public boolean a0;
    public int a1;
    public boolean b;
    public boolean b0;
    public int b1;
    public boolean c;
    public boolean c0;
    public boolean c1;
    public String d;
    public boolean d0;
    public boolean d1;
    public String e;
    public boolean e0;
    public boolean e1;
    public String f;
    public boolean f0;
    public int f1;
    public String g;
    public boolean g0;
    public boolean g1;
    public String h;
    public boolean h0;
    public boolean h1;
    public String i;
    public boolean i0;
    public boolean i1;
    public String j;
    public boolean j0;
    public boolean j1;
    public String k;
    public boolean k0;
    public boolean k1;
    public boolean l;
    public boolean l0;
    public boolean l1;
    public String m;
    public boolean m0;
    public String m1;
    public String n;
    public boolean n0;
    public boolean n1;
    public String o;
    public boolean o0;
    public int o1;
    public int p;
    public boolean p0;
    public boolean p1;

    /* JADX INFO: renamed from: q, reason: collision with root package name */
    public int f298q;
    public boolean q0;
    public boolean q1;
    public int r;
    public boolean r0;
    public boolean r1;
    public boolean s;
    public int s0;
    public boolean s1;
    public boolean t;
    public int t0;
    public boolean t1;
    public int u;
    public int u0;
    public int v;
    public int v0;
    public int w;
    public boolean w0;
    public int x;
    public boolean x0;
    public int y;
    public boolean y0;
    public int z;
    public boolean z0;
    public static PictureWindowAnimationStyle v1 = PictureWindowAnimationStyle.a();
    public static final Parcelable.Creator<PictureSelectionConfig> CREATOR = new a();

    class a implements Parcelable.Creator {
        a() {
        }

        @Override // android.os.Parcelable.Creator
        /* JADX INFO: renamed from: a, reason: merged with bridge method [inline-methods] */
        public PictureSelectionConfig createFromParcel(Parcel parcel) {
            return new PictureSelectionConfig(parcel);
        }

        @Override // android.os.Parcelable.Creator
        /* JADX INFO: renamed from: b, reason: merged with bridge method [inline-methods] */
        public PictureSelectionConfig[] newArray(int i) {
            return new PictureSelectionConfig[i];
        }
    }

    private static final class b {
        private static final PictureSelectionConfig a = new PictureSelectionConfig();
    }

    protected PictureSelectionConfig(Parcel parcel) {
        this.a = a22.w();
        this.b = false;
        this.p = -1;
        this.f298q = 259;
        this.u = R$style.picture_default_style;
        this.v = 2;
        this.w = 9;
        this.x = 0;
        this.y = 1;
        this.z = 0;
        this.F = 1;
        this.G = 90;
        this.J = 60;
        this.L = 100;
        this.M = 4;
        this.R = 80;
        this.U = PlaybackStateCompat.ACTION_PLAY_FROM_MEDIA_ID;
        this.V = -2;
        this.f0 = true;
        this.a1 = -1;
        this.b1 = 60;
        this.c1 = true;
        this.f1 = -1;
        this.g1 = true;
        this.i1 = true;
        this.j1 = true;
        this.k1 = true;
        this.l1 = false;
        this.n1 = true;
        this.o1 = a22.s();
        this.a = parcel.readInt();
        this.b = parcel.readByte() != 0;
        this.c = parcel.readByte() != 0;
        this.d = parcel.readString();
        this.e = parcel.readString();
        this.f = parcel.readString();
        this.g = parcel.readString();
        this.h = parcel.readString();
        this.i = parcel.readString();
        this.j = parcel.readString();
        this.k = parcel.readString();
        this.l = parcel.readByte() != 0;
        this.m = parcel.readString();
        this.n = parcel.readString();
        this.o = parcel.readString();
        this.p = parcel.readInt();
        this.f298q = parcel.readInt();
        this.r = parcel.readInt();
        this.s = parcel.readByte() != 0;
        this.t = parcel.readByte() != 0;
        this.u = parcel.readInt();
        this.v = parcel.readInt();
        this.w = parcel.readInt();
        this.x = parcel.readInt();
        this.y = parcel.readInt();
        this.z = parcel.readInt();
        this.F = parcel.readInt();
        this.G = parcel.readInt();
        this.H = parcel.readInt();
        this.I = parcel.readInt();
        this.J = parcel.readInt();
        this.K = parcel.readInt();
        this.L = parcel.readInt();
        this.M = parcel.readInt();
        this.N = parcel.readInt();
        this.O = parcel.readInt();
        this.P = parcel.readInt();
        this.Q = parcel.readInt();
        this.R = parcel.readInt();
        this.S = parcel.readFloat();
        this.T = parcel.readLong();
        this.U = parcel.readLong();
        this.V = parcel.readInt();
        this.W = parcel.readByte() != 0;
        this.X = parcel.readByte() != 0;
        this.Y = parcel.readByte() != 0;
        this.Z = parcel.readByte() != 0;
        this.a0 = parcel.readByte() != 0;
        this.b0 = parcel.readByte() != 0;
        this.c0 = parcel.readByte() != 0;
        this.d0 = parcel.readByte() != 0;
        this.e0 = parcel.readByte() != 0;
        this.f0 = parcel.readByte() != 0;
        this.g0 = parcel.readByte() != 0;
        this.h0 = parcel.readByte() != 0;
        this.i0 = parcel.readByte() != 0;
        this.j0 = parcel.readByte() != 0;
        this.k0 = parcel.readByte() != 0;
        this.l0 = parcel.readByte() != 0;
        this.m0 = parcel.readByte() != 0;
        this.n0 = parcel.readByte() != 0;
        this.o0 = parcel.readByte() != 0;
        this.p0 = parcel.readByte() != 0;
        this.q0 = parcel.readByte() != 0;
        this.r0 = parcel.readByte() != 0;
        this.s0 = parcel.readInt();
        this.t0 = parcel.readInt();
        this.u0 = parcel.readInt();
        this.v0 = parcel.readInt();
        this.w0 = parcel.readByte() != 0;
        this.x0 = parcel.readByte() != 0;
        this.y0 = parcel.readByte() != 0;
        this.z0 = parcel.readByte() != 0;
        this.A0 = parcel.readByte() != 0;
        this.B0 = parcel.readByte() != 0;
        this.C0 = parcel.readByte() != 0;
        this.D0 = parcel.readByte() != 0;
        this.E0 = parcel.readByte() != 0;
        this.F0 = parcel.readByte() != 0;
        this.G0 = parcel.readByte() != 0;
        this.I0 = parcel.createTypedArrayList(LocalMedia.CREATOR);
        this.K0 = parcel.readString();
        this.L0 = parcel.readByte() != 0;
        this.M0 = parcel.readByte() != 0;
        this.N0 = parcel.readByte() != 0;
        this.O0 = parcel.readByte() != 0;
        this.P0 = parcel.readInt();
        this.Q0 = parcel.readInt();
        this.R0 = parcel.readInt();
        this.S0 = parcel.readInt();
        this.T0 = parcel.readInt();
        this.U0 = parcel.readInt();
        this.V0 = parcel.readInt();
        this.W0 = parcel.readString();
        this.X0 = parcel.readString();
        this.Y0 = parcel.readString();
        this.Z0 = parcel.readString();
        this.a1 = parcel.readInt();
        this.b1 = parcel.readInt();
        this.c1 = parcel.readByte() != 0;
        this.d1 = parcel.readByte() != 0;
        this.e1 = parcel.readByte() != 0;
        this.f1 = parcel.readInt();
        this.g1 = parcel.readByte() != 0;
        this.h1 = parcel.readByte() != 0;
        this.i1 = parcel.readByte() != 0;
        this.j1 = parcel.readByte() != 0;
        this.k1 = parcel.readByte() != 0;
        this.l1 = parcel.readByte() != 0;
        this.m1 = parcel.readString();
        this.n1 = parcel.readByte() != 0;
        this.o1 = parcel.readInt();
        this.p1 = parcel.readByte() != 0;
        this.q1 = parcel.readByte() != 0;
        this.r1 = parcel.readByte() != 0;
        this.s1 = parcel.readByte() != 0;
        this.t1 = parcel.readByte() != 0;
    }

    public static void a() {
        x1 = null;
        w1 = null;
    }

    public static PictureSelectionConfig b() {
        PictureSelectionConfig pictureSelectionConfigC = c();
        pictureSelectionConfigC.d();
        return pictureSelectionConfigC;
    }

    public static PictureSelectionConfig c() {
        return b.a;
    }

    protected void d() {
        this.a = a22.w();
        this.b = false;
        this.u = R$style.picture_default_style;
        this.v = 2;
        u1 = null;
        this.w = 9;
        this.x = 0;
        this.y = 1;
        this.z = 0;
        this.F = 1;
        this.V = -2;
        this.G = 90;
        this.H = 0;
        this.I = 0;
        this.S = 0.0f;
        this.T = 0L;
        this.U = PlaybackStateCompat.ACTION_PLAY_FROM_MEDIA_ID;
        this.J = 60;
        this.K = 0;
        this.R = 80;
        this.M = 4;
        this.b0 = false;
        this.c0 = false;
        this.N = 0;
        this.O = 0;
        this.P = 0;
        this.Q = 0;
        this.s = false;
        this.G0 = false;
        this.t = false;
        this.f0 = true;
        this.g0 = false;
        this.h0 = true;
        this.i0 = true;
        this.l = false;
        this.L0 = false;
        this.c = false;
        this.j0 = true;
        this.k0 = true;
        this.l0 = true;
        this.m0 = false;
        this.F0 = false;
        this.n0 = false;
        this.r1 = false;
        this.s1 = true;
        this.t1 = true;
        this.o0 = false;
        this.Y = false;
        this.Z = false;
        this.X = true;
        this.W = true;
        this.p0 = false;
        this.q0 = false;
        this.r0 = false;
        this.w0 = true;
        this.x0 = true;
        this.y0 = true;
        this.z0 = true;
        this.A0 = true;
        this.B0 = false;
        this.D0 = false;
        this.C0 = true;
        this.a0 = true;
        this.s0 = 0;
        this.t0 = 0;
        this.u0 = 1;
        this.E0 = true;
        this.d = Constants.STR_EMPTY;
        this.e = Constants.STR_EMPTY;
        this.f = Constants.STR_EMPTY;
        this.g = Constants.STR_EMPTY;
        this.h = Constants.STR_EMPTY;
        this.i = Constants.STR_EMPTY;
        this.j = Constants.STR_EMPTY;
        this.k = Constants.STR_EMPTY;
        this.K0 = Constants.STR_EMPTY;
        this.o = Constants.STR_EMPTY;
        this.m = Constants.STR_EMPTY;
        this.n = Constants.STR_EMPTY;
        this.J0 = null;
        this.I0 = new ArrayList();
        this.H0 = null;
        this.P0 = 0;
        this.Q0 = 0;
        this.R0 = 0;
        this.S0 = 0;
        this.T0 = 0;
        this.U0 = 0;
        this.V0 = 0;
        this.M0 = false;
        this.N0 = false;
        this.O0 = false;
        this.W0 = Constants.STR_EMPTY;
        this.X0 = Constants.STR_EMPTY;
        this.Y0 = Constants.STR_EMPTY;
        this.Z0 = Constants.STR_EMPTY;
        this.a1 = -1;
        this.b1 = 60;
        this.c1 = true;
        this.d1 = false;
        this.e1 = false;
        this.f1 = -1;
        this.g1 = true;
        this.h1 = false;
        this.i1 = true;
        this.j1 = true;
        this.k1 = true;
        this.l1 = !ol2.a();
        this.m1 = Constants.STR_EMPTY;
        this.n1 = true;
        this.v0 = -1;
        this.e0 = false;
        this.d0 = true;
        this.o1 = a22.s();
        this.p1 = false;
        this.q1 = false;
    }

    @Override // android.os.Parcelable
    public int describeContents() {
        return 0;
    }

    @Override // android.os.Parcelable
    public void writeToParcel(Parcel parcel, int i) {
        parcel.writeInt(this.a);
        parcel.writeByte(this.b ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.c ? (byte) 1 : (byte) 0);
        parcel.writeString(this.d);
        parcel.writeString(this.e);
        parcel.writeString(this.f);
        parcel.writeString(this.g);
        parcel.writeString(this.h);
        parcel.writeString(this.i);
        parcel.writeString(this.j);
        parcel.writeString(this.k);
        parcel.writeByte(this.l ? (byte) 1 : (byte) 0);
        parcel.writeString(this.m);
        parcel.writeString(this.n);
        parcel.writeString(this.o);
        parcel.writeInt(this.p);
        parcel.writeInt(this.f298q);
        parcel.writeInt(this.r);
        parcel.writeByte(this.s ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.t ? (byte) 1 : (byte) 0);
        parcel.writeInt(this.u);
        parcel.writeInt(this.v);
        parcel.writeInt(this.w);
        parcel.writeInt(this.x);
        parcel.writeInt(this.y);
        parcel.writeInt(this.z);
        parcel.writeInt(this.F);
        parcel.writeInt(this.G);
        parcel.writeInt(this.H);
        parcel.writeInt(this.I);
        parcel.writeInt(this.J);
        parcel.writeInt(this.K);
        parcel.writeInt(this.L);
        parcel.writeInt(this.M);
        parcel.writeInt(this.N);
        parcel.writeInt(this.O);
        parcel.writeInt(this.P);
        parcel.writeInt(this.Q);
        parcel.writeInt(this.R);
        parcel.writeFloat(this.S);
        parcel.writeLong(this.T);
        parcel.writeLong(this.U);
        parcel.writeInt(this.V);
        parcel.writeByte(this.W ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.X ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.Y ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.Z ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.a0 ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.b0 ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.c0 ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.d0 ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.e0 ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.f0 ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.g0 ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.h0 ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.i0 ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.j0 ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.k0 ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.l0 ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.m0 ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.n0 ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.o0 ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.p0 ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.q0 ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.r0 ? (byte) 1 : (byte) 0);
        parcel.writeInt(this.s0);
        parcel.writeInt(this.t0);
        parcel.writeInt(this.u0);
        parcel.writeInt(this.v0);
        parcel.writeByte(this.w0 ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.x0 ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.y0 ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.z0 ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.A0 ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.B0 ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.C0 ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.D0 ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.E0 ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.F0 ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.G0 ? (byte) 1 : (byte) 0);
        parcel.writeTypedList(this.I0);
        parcel.writeString(this.K0);
        parcel.writeByte(this.L0 ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.M0 ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.N0 ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.O0 ? (byte) 1 : (byte) 0);
        parcel.writeInt(this.P0);
        parcel.writeInt(this.Q0);
        parcel.writeInt(this.R0);
        parcel.writeInt(this.S0);
        parcel.writeInt(this.T0);
        parcel.writeInt(this.U0);
        parcel.writeInt(this.V0);
        parcel.writeString(this.W0);
        parcel.writeString(this.X0);
        parcel.writeString(this.Y0);
        parcel.writeString(this.Z0);
        parcel.writeInt(this.a1);
        parcel.writeInt(this.b1);
        parcel.writeByte(this.c1 ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.d1 ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.e1 ? (byte) 1 : (byte) 0);
        parcel.writeInt(this.f1);
        parcel.writeByte(this.g1 ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.h1 ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.i1 ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.j1 ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.k1 ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.l1 ? (byte) 1 : (byte) 0);
        parcel.writeString(this.m1);
        parcel.writeByte(this.n1 ? (byte) 1 : (byte) 0);
        parcel.writeInt(this.o1);
        parcel.writeByte(this.p1 ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.q1 ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.r1 ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.s1 ? (byte) 1 : (byte) 0);
        parcel.writeByte(this.t1 ? (byte) 1 : (byte) 0);
    }

    public PictureSelectionConfig() {
        this.a = a22.w();
        this.b = false;
        this.p = -1;
        this.f298q = 259;
        this.u = R$style.picture_default_style;
        this.v = 2;
        this.w = 9;
        this.x = 0;
        this.y = 1;
        this.z = 0;
        this.F = 1;
        this.G = 90;
        this.J = 60;
        this.L = 100;
        this.M = 4;
        this.R = 80;
        this.U = PlaybackStateCompat.ACTION_PLAY_FROM_MEDIA_ID;
        this.V = -2;
        this.f0 = true;
        this.a1 = -1;
        this.b1 = 60;
        this.c1 = true;
        this.f1 = -1;
        this.g1 = true;
        this.i1 = true;
        this.j1 = true;
        this.k1 = true;
        this.l1 = false;
        this.n1 = true;
        this.o1 = a22.s();
    }
}
